2. Matrix Multiplication in PyTorch

Matrix multiplication is essential for neural networks! PyTorch provides efficient operations for multiplying matrices and tensors.

import torch

In [1]:
import torch

1. Matrix Multiplication (@ operator)

Use the @ operator or torch.matmul() for matrix multiplication! A @ B multiplies matrices A and B.

In [2]:
# Create two matrices
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print(f"Shape: {A.shape}")
print()

print("Matrix B:")
print(B)
print(f"Shape: {B.shape}")
print()

# Matrix multiplication using @
result = A @ B
print("A @ B (matrix multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# Using torch.matmul()
result2 = torch.matmul(A, B)
print("torch.matmul(A, B):")
print(result2)
print("(Same result!)")

Matrix A:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])
Shape: torch.Size([2, 2])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])
Shape: torch.Size([2, 2])

torch.matmul(A, B):
tensor([[19., 22.],
        [43., 50.]])
(Same result!)


2. Matrix-Vector Multiplication

Multiply a matrix by a vector to transform it!

In [3]:
# Matrix-vector multiplication
M = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

v = torch.tensor([5, 6], dtype=torch.float32)

print("Matrix M:")
print(M)
print(f"Shape: {M.shape}")
print()

print("Vector v:")
print(v)
print(f"Shape: {v.shape}")
print()

# Matrix × Vector
result = M @ v
print("M @ v (matrix-vector multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# How it works
print("How it works:")
print(f"Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = {M[0, 0]}*{v[0]} + {M[0, 1]}*{v[1]} = {result[0]}")
print(f"Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = {M[1, 0]}*{v[0]} + {M[1, 1]}*{v[1]} = {result[1]}")

Matrix M:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Vector v:
tensor([5., 6.])
Shape: torch.Size([2])

M @ v (matrix-vector multiplication):
tensor([17., 39.])
Shape: torch.Size([2])

How it works:
Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = 1.0*5.0 + 2.0*6.0 = 17.0
Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = 3.0*5.0 + 4.0*6.0 = 39.0


3. Batch Matrix Multiplication

Process multiple matrices at once using batch dimensions! Very useful for neural networks!

In [4]:
# Batch matrix multiplication
# Create batch of matrices: (batch_size, rows, cols)
batch_A = torch.randn(3, 2, 4)  # 3 matrices, each 2×4
batch_B = torch.randn(3, 4, 3)  # 3 matrices, each 4×3

print("Batch A (3 matrices, each 2×4):")
print(batch_A)
print(f"Shape: {batch_A.shape}")
print()

print("Batch B (3 matrices, each 4×3):")
print(batch_B)
print(f"Shape: {batch_B.shape}")
print()

# Batch matrix multiplication
batch_result = torch.bmm(batch_A, batch_B)
print("Batch matrix multiplication result:")
print(batch_result)
print(f"Shape: {batch_result.shape}")
print("(3 matrices, each 2×3)")
print()

# Verify: first matrix multiplication
A0 = batch_A[0]
B0 = batch_B[0]
result0 = A0 @ B0

print("First matrix multiplication (manual):")
print(result0)
print()

print("First matrix multiplication (from batch):")
print(batch_result[0])
print("(Should match!)")
print(f"Are they equal? {torch.allclose(result0, batch_result[0])}")

Batch A (3 matrices, each 2×4):
tensor([[[ 0.7605,  0.0402, -0.2906,  0.0152],
         [-1.9678, -0.5835,  0.3091, -0.2016]],

        [[-0.4556, -0.6437,  1.5097, -0.8477],
         [-0.6783, -1.2023, -0.6526, -1.0351]],

        [[-1.9344,  1.4223,  1.6967,  0.3081],
         [ 0.4368,  0.0716, -0.5698,  0.6517]]])
Shape: torch.Size([3, 2, 4])

Batch B (3 matrices, each 4×3):
tensor([[[-1.1001e+00,  1.4180e-01, -1.2720e+00],
         [-1.6821e+00,  7.9951e-01,  9.1602e-01],
         [-7.8651e-01,  2.9661e-01, -3.2509e-01],
         [-6.4207e-01, -9.9768e-02,  1.3440e+00]],

        [[ 1.9384e+00, -2.0912e-02,  7.3835e-01],
         [-4.1677e-01,  1.8967e+00, -1.0052e+00],
         [-1.9268e-01,  6.7957e-01, -1.1346e-01],
         [-1.3281e-01, -7.9538e-01,  1.1167e+00]],

        [[ 8.4058e-02, -9.1536e-01, -6.2801e-02],
         [ 1.4183e-01,  5.1811e-01,  1.2779e+00],
         [-1.2815e+00,  7.3812e-01, -1.8452e-04],
         [-8.9825e-01, -8.8986e-01, -1.0844e-01]]])
Shape: torch

4. Element-wise Multiplication

Multiply elements at the same position (not matrix multiplication)! Use * for element-wise multiplication.

In [5]:
# Element-wise multiplication (different from matrix multiplication!)
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

# Element-wise multiplication
element_wise = A * B
print("A * B (element-wise multiplication):")
print(element_wise)
print()

# Matrix multiplication (for comparison)
matrix_mult = A @ B
print("A @ B (matrix multiplication):")
print(matrix_mult)
print()

print("Notice: Element-wise (*) is different from matrix multiplication (@)!")
print(f"Element-wise: {A[0, 0]} * {B[0, 0]} = {element_wise[0, 0]}")
print(f"Matrix mult: A[0, 0]*B[0, 0] + A[0, 1]*B[1, 0] = {matrix_mult[0, 0]}")

Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])

A * B (element-wise multiplication):
tensor([[ 5., 12.],
        [21., 32.]])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])

Notice: Element-wise (*) is different from matrix multiplication (@)!
Element-wise: 1.0 * 5.0 = 5.0
Matrix mult: A[0, 0]*B[0, 0] + A[0, 1]*B[1, 0] = 19.0
